<?php

/**
 * BasePocatek
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property enum $typ_uctu
 * @property enum $mena
 * @property double $stav
 * @property double $urok
 * 
 * @method enum    getTypUctu()  Returns the current record's "typ_uctu" value
 * @method enum    getMena()     Returns the current record's "mena" value
 * @method double  getStav()     Returns the current record's "stav" value
 * @method double  getUrok()     Returns the current record's "urok" value
 * @method Pocatek setTypUctu()  Sets the current record's "typ_uctu" value
 * @method Pocatek setMena()     Sets the current record's "mena" value
 * @method Pocatek setStav()     Sets the current record's "stav" value
 * @method Pocatek setUrok()     Sets the current record's "urok" value
 * 
 * @package    iqPegas konfig
 * @subpackage model
 * @author     Jan Damek
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePocatek extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('pocatek');
        $this->hasColumn('typ_uctu', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'bu',
              1 => 'sp',
             ),
             ));
        $this->hasColumn('mena', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'CZK',
              1 => 'USD',
              2 => 'EUR',
             ),
             ));
        $this->hasColumn('stav', 'double', null, array(
             'type' => 'double',
             ));
        $this->hasColumn('urok', 'double', null, array(
             'type' => 'double',
             ));


        $this->index('name_index', array(
             'fields' => 
             array(
              'typ_uctu' => 
              array(
              ),
              'mena' => 
              array(
              ),
             ),
             'type' => 'unique',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}