<?php

/**
 * BaseBlokace
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property date $datum
 * @property double $castka
 * @property enum $karta
 * @property enum $mena
 * @property string $obchod
 * @property enum $typ
 * @property string $misto
 * @property boolean $realizovano
 * 
 * @method integer getId()          Returns the current record's "id" value
 * @method date    getDatum()       Returns the current record's "datum" value
 * @method double  getCastka()      Returns the current record's "castka" value
 * @method enum    getKarta()       Returns the current record's "karta" value
 * @method enum    getMena()        Returns the current record's "mena" value
 * @method string  getObchod()      Returns the current record's "obchod" value
 * @method enum    getTyp()         Returns the current record's "typ" value
 * @method string  getMisto()       Returns the current record's "misto" value
 * @method boolean getRealizovano() Returns the current record's "realizovano" value
 * @method Blokace setId()          Sets the current record's "id" value
 * @method Blokace setDatum()       Sets the current record's "datum" value
 * @method Blokace setCastka()      Sets the current record's "castka" value
 * @method Blokace setKarta()       Sets the current record's "karta" value
 * @method Blokace setMena()        Sets the current record's "mena" value
 * @method Blokace setObchod()      Sets the current record's "obchod" value
 * @method Blokace setTyp()         Sets the current record's "typ" value
 * @method Blokace setMisto()       Sets the current record's "misto" value
 * @method Blokace setRealizovano() Sets the current record's "realizovano" value
 * 
 * @package    iqPegas konfig
 * @subpackage model
 * @author     Jan Damek
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseBlokace extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('blokace');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('datum', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('castka', 'double', null, array(
             'type' => 'double',
             ));
        $this->hasColumn('karta', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'PK: 408364XXXXXX2884',
              1 => 'PK: 408359XXXXXX6465',
             ),
             ));
        $this->hasColumn('mena', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'CZK',
              1 => 'USD',
              2 => 'EUR',
             ),
             ));
        $this->hasColumn('obchod', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('typ', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'Platba kartou',
              1 => 'Výběr z bankomatu',
             ),
             ));
        $this->hasColumn('misto', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('realizovano', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}