<?php

/**
 * BaseSms
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $kdo
 * @property string $kod
 * @property string $obsah
 * @property boolean $odeslano
 * @property boolean $overeno
 * 
 * @method integer getId()       Returns the current record's "id" value
 * @method string  getKdo()      Returns the current record's "kdo" value
 * @method string  getKod()      Returns the current record's "kod" value
 * @method string  getObsah()    Returns the current record's "obsah" value
 * @method boolean getOdeslano() Returns the current record's "odeslano" value
 * @method boolean getOvereno()  Returns the current record's "overeno" value
 * @method Sms     setId()       Sets the current record's "id" value
 * @method Sms     setKdo()      Sets the current record's "kdo" value
 * @method Sms     setKod()      Sets the current record's "kod" value
 * @method Sms     setObsah()    Sets the current record's "obsah" value
 * @method Sms     setOdeslano() Sets the current record's "odeslano" value
 * @method Sms     setOvereno()  Sets the current record's "overeno" value
 * 
 * @package    iqPegas konfig
 * @subpackage model
 * @author     Jan Damek
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSms extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('sms');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('kdo', 'string', 20, array(
             'type' => 'string',
             'length' => 20,
             ));
        $this->hasColumn('kod', 'string', 20, array(
             'type' => 'string',
             'length' => 20,
             ));
        $this->hasColumn('obsah', 'string', 1500, array(
             'type' => 'string',
             'length' => 1500,
             ));
        $this->hasColumn('odeslano', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));
        $this->hasColumn('overeno', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}