<?php

/**
 * BaseReserved
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $word
 * 
 * @method integer  getId()   Returns the current record's "id" value
 * @method string   getWord() Returns the current record's "word" value
 * @method Reserved setId()   Sets the current record's "id" value
 * @method Reserved setWord() Sets the current record's "word" value
 * 
 * @package    iqPegas konfig
 * @subpackage model
 * @author     Jan Damek
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseReserved extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('reserved');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('word', 'string', 50, array(
             'type' => 'string',
             'notnull' => false,
             'unique' => false,
             'length' => 50,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}