<?php

/**
 * BaseTexty
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property enum $typ
 * @property clob $text
 * 
 * @method enum  getTyp()  Returns the current record's "typ" value
 * @method clob  getText() Returns the current record's "text" value
 * @method Texty setTyp()  Sets the current record's "typ" value
 * @method Texty setText() Sets the current record's "text" value
 * 
 * @package    iqPegas konfig
 * @subpackage model
 * @author     Jan Damek
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTexty extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('texty');
        $this->hasColumn('typ', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'potvrzeni mailu',
              1 => 'neni hash',
              2 => 'neni mail',
              3 => 'hashin proccess',
              4 => 'Zaslat novy hash na email',
              5 => 'NeniTextMailu',
              6 => 'MailJizOdeslan',
              7 => 'Pro tento hash',
              8 => 'NastalaChyba',
              9 => 'LinkNaNovyMain',
              10 => 'linkNovyMainLink',
              11 => 'Odeslani emailu',
              12 => 'na Vami uvedeny email',
              13 => 'novylink',
              14 => 'neni hash',
              15 => 'naMailBylOdeslanNovyHash',
              16 => 'potvrzeni_registrace_mailu',
             ),
             'unique' => true,
             ));
        $this->hasColumn('text', 'clob', null, array(
             'type' => 'clob',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $i18n0 = new Doctrine_Template_I18n(array(
             'fields' => 
             array(
              0 => 'text',
             ),
             ));
        $this->actAs($i18n0);
    }
}