<?php

/**
 * BaseRegistration_check
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $reg_id
 * @property string $hesh
 * @property boolean $in_process
 * @property Registration $Registration
 * 
 * @method integer            getId()           Returns the current record's "id" value
 * @method integer            getRegId()        Returns the current record's "reg_id" value
 * @method string             getHesh()         Returns the current record's "hesh" value
 * @method boolean            getInProcess()    Returns the current record's "in_process" value
 * @method Registration       getRegistration() Returns the current record's "Registration" value
 * @method Registration_check setId()           Sets the current record's "id" value
 * @method Registration_check setRegId()        Sets the current record's "reg_id" value
 * @method Registration_check setHesh()         Sets the current record's "hesh" value
 * @method Registration_check setInProcess()    Sets the current record's "in_process" value
 * @method Registration_check setRegistration() Sets the current record's "Registration" value
 * 
 * @package    iqPegas konfig
 * @subpackage model
 * @author     Jan Damek
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRegistration_check extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('registration_check');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('reg_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('hesh', 'string', 32, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 32,
             ));
        $this->hasColumn('in_process', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Registration', array(
             'local' => 'reg_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}