<?php

/**
 * BaseRegistration
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property string $domain
 * @property string $email
 * @property boolean $checked
 * @property Doctrine_Collection $Registration_check
 * @property Doctrine_Collection $Registration_complet
 * @property Doctrine_Collection $SendedEmail
 * 
 * @method integer             getId()                   Returns the current record's "id" value
 * @method string              getName()                 Returns the current record's "name" value
 * @method string              getDomain()               Returns the current record's "domain" value
 * @method string              getEmail()                Returns the current record's "email" value
 * @method boolean             getChecked()              Returns the current record's "checked" value
 * @method Doctrine_Collection getRegistrationCheck()    Returns the current record's "Registration_check" collection
 * @method Doctrine_Collection getRegistrationComplet()  Returns the current record's "Registration_complet" collection
 * @method Doctrine_Collection getSendedEmail()          Returns the current record's "SendedEmail" collection
 * @method Registration        setId()                   Sets the current record's "id" value
 * @method Registration        setName()                 Sets the current record's "name" value
 * @method Registration        setDomain()               Sets the current record's "domain" value
 * @method Registration        setEmail()                Sets the current record's "email" value
 * @method Registration        setChecked()              Sets the current record's "checked" value
 * @method Registration        setRegistrationCheck()    Sets the current record's "Registration_check" collection
 * @method Registration        setRegistrationComplet()  Sets the current record's "Registration_complet" collection
 * @method Registration        setSendedEmail()          Sets the current record's "SendedEmail" collection
 * 
 * @package    iqPegas konfig
 * @subpackage model
 * @author     Jan Damek
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRegistration extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('registration');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('name', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 50,
             ));
        $this->hasColumn('domain', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 50,
             ));
        $this->hasColumn('email', 'string', 150, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 150,
             ));
        $this->hasColumn('checked', 'boolean', null, array(
             'type' => 'boolean',
             'default' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Registration_check', array(
             'local' => 'id',
             'foreign' => 'reg_id'));

        $this->hasMany('Registration_complet', array(
             'local' => 'id',
             'foreign' => 'reg_id'));

        $this->hasMany('SendedEmail', array(
             'local' => 'id',
             'foreign' => 'reg_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}