<?php

/**
 * BaseRegistration_complet
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $reg_id
 * @property string $password
 * @property string $gen_password
 * @property Registration $Registration
 * 
 * @method integer              getId()           Returns the current record's "id" value
 * @method integer              getRegId()        Returns the current record's "reg_id" value
 * @method string               getPassword()     Returns the current record's "password" value
 * @method string               getGenPassword()  Returns the current record's "gen_password" value
 * @method Registration         getRegistration() Returns the current record's "Registration" value
 * @method Registration_complet setId()           Sets the current record's "id" value
 * @method Registration_complet setRegId()        Sets the current record's "reg_id" value
 * @method Registration_complet setPassword()     Sets the current record's "password" value
 * @method Registration_complet setGenPassword()  Sets the current record's "gen_password" value
 * @method Registration_complet setRegistration() Sets the current record's "Registration" value
 * 
 * @package    iqPegas konfig
 * @subpackage model
 * @author     Jan Damek
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRegistration_complet extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('registration_complet');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('reg_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('password', 'string', 32, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 32,
             ));
        $this->hasColumn('gen_password', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Registration', array(
             'local' => 'reg_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}