<?php

/**
 * BaseZpravy
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property enum $typ_uctu
 * @property enum $mena
 * @property date $datum
 * @property string $popis
 * @property clob $text
 * @property boolean $precteno
 * 
 * @method enum    getTypUctu()  Returns the current record's "typ_uctu" value
 * @method enum    getMena()     Returns the current record's "mena" value
 * @method date    getDatum()    Returns the current record's "datum" value
 * @method string  getPopis()    Returns the current record's "popis" value
 * @method clob    getText()     Returns the current record's "text" value
 * @method boolean getPrecteno() Returns the current record's "precteno" value
 * @method Zpravy  setTypUctu()  Sets the current record's "typ_uctu" value
 * @method Zpravy  setMena()     Sets the current record's "mena" value
 * @method Zpravy  setDatum()    Sets the current record's "datum" value
 * @method Zpravy  setPopis()    Sets the current record's "popis" value
 * @method Zpravy  setText()     Sets the current record's "text" value
 * @method Zpravy  setPrecteno() Sets the current record's "precteno" value
 * 
 * @package    iqPegas konfig
 * @subpackage model
 * @author     Jan Damek
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseZpravy extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('zpravy');
        $this->hasColumn('typ_uctu', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'bu',
              1 => 'sp',
             ),
             ));
        $this->hasColumn('mena', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'CZK',
              1 => 'USD',
              2 => 'EUR',
             ),
             ));
        $this->hasColumn('datum', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('popis', 'string', 200, array(
             'type' => 'string',
             'length' => 200,
             ));
        $this->hasColumn('text', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('precteno', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}