zpravy:
  class: sfDoctrineRouteCollection
  options:
    model:                zpravy
    module:               zpravy
    prefix_path:          /zpravy
    column:               id
    with_wildcard_routes: true

pocatek:
  class: sfDoctrineRouteCollection
  options:
    model:                pocatek
    module:               pocatek
    prefix_path:          /pocatek
    column:               id
    with_wildcard_routes: true

kurz:
  class: sfDoctrineRouteCollection
  options:
    model:                kurz
    module:               kurz
    prefix_path:          /kurz
    column:               id
    with_wildcard_routes: true

blokace:
  class: sfDoctrineRouteCollection
  options:
    model:                blokace
    module:               blokace
    prefix_path:          /blokace
    column:               id
    with_wildcard_routes: true

sms:
  class: sfDoctrineRouteCollection
  options:
    model:                sms
    module:               sms
    prefix_path:          /sms
    column:               id
    with_wildcard_routes: true

pohyby:
  class: sfDoctrineRouteCollection
  options:
    model:                pohyby
    module:               pohyby
    prefix_path:          /pohyby
    column:               id
    with_wildcard_routes: true

texty:
  class: sfDoctrineRouteCollection
  options:
    model:                Texty
    module:               texty
    prefix_path:          /texty
    column:               id
    with_wildcard_routes: true

email_texts:
  class: sfDoctrineRouteCollection
  options:
    model:                EmailTexts
    module:               email_texts
    prefix_path:          /email_texts
    column:               id
    with_wildcard_routes: true

sended_email:
  class: sfDoctrineRouteCollection
  options:
    model:                SendedEmail
    module:               sended_email
    prefix_path:          /sended_email
    column:               id
    with_wildcard_routes: true

notallowed:
  class: sfDoctrineRouteCollection
  options:
    model:                Notallowed
    module:               notallowed
    prefix_path:          /notallowed
    column:               id
    with_wildcard_routes: true

reserved:
  class: sfDoctrineRouteCollection
  options:
    model:                Reserved
    module:               reserved
    prefix_path:          /reserved
    column:               id
    with_wildcard_routes: true

registration_complet:
  class: sfDoctrineRouteCollection
  options:
    model:                Registration_complet
    module:               registration_complet
    prefix_path:          /registration_complet
    column:               id
    with_wildcard_routes: true

registration_check:
  class: sfDoctrineRouteCollection
  options:
    model:                Registration_check
    module:               registration_check
    prefix_path:          /registration_check
    column:               id
    with_wildcard_routes: true

registration:
  class: sfDoctrineRouteCollection
  options:
    model:                Registration
    module:               registration
    prefix_path:          /registration
    column:               id
    with_wildcard_routes: true

# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules
homepage:
  url:   /
  param: { module: registration_complet, action: index }

# generic rules
# please, remove them by adding more specific rules
default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
