<?php

/**
 * BlokaceTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BlokaceTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object BlokaceTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Blokace');
    }
}