<?php

/**
 * EmailTextsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EmailTextsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EmailTextsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('EmailTexts');
    }
}