<?php

/**
 * PocatekTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PocatekTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PocatekTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Pocatek');
    }
}