<?php

/**
 * PohybyTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PohybyTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PohybyTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Pohyby');
    }
}