<?php

/**
 * Registration_completTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Registration_completTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Registration_completTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Registration_complet');
    }
}