<?php

/**
 * Registration_checkTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Registration_checkTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Registration_checkTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Registration_check');
    }
}