<?php

/**
 * ReservedTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ReservedTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ReservedTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Reserved');
    }
}