<?php

/**
 * SendedEmailTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SendedEmailTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SendedEmailTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SendedEmail');
    }
}