<?php

/**
 * SmsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SmsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SmsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Sms');
    }
}