<?php

/**
 * ZpravyTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ZpravyTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ZpravyTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Zpravy');
    }
}