<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2014/06/07 16:18:09

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=iqpegas',
  'username' => 'iqpegas',
  'password' => 'iY2yM3Rs2WlO',
  'attributes' => 
  array (
    'default_table_collate' => 'utf8_czech_ci',
    'default_table_charset' => 'utf8',
  ),
  'name' => 'doctrine',
)),);
