generator:
  class: sfDoctrineGenerator
  param:
    model_class:           blokace
    theme:                 jroller
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          blokace
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:    
          display: [=datum, =karta, mena, castka, obchod]
          sort: [datum, desc]
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
