generator:
  class: sfDoctrineGenerator
  param:
    model_class:           sms
    theme:                 jroller
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          sms
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:    
        title: Seznam sms
        display: [=id, =kdo, obsah, =kod, odeslano]   
        sort: [id, desc]
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
